type Error {
    message: String!
}

type ApiResponse {
    status: Int!
    prices: [Price]!
    errors: [Error]!
}

type Price {
    fromCurrency: String!
    price: String!
    toCurrency: String!
    date: String!
}


type Query {
    getCryptoCurrencyPrice(
        fromCurrency: String!
        toCurrency: String!
    ): ApiResponse!
}
